collections:
  episodes:
    output: true

defaults:
  -
    scope:
      path: ""
      type: episodes
    values:
      layout: episode
      excerpt_separator: <!--end of quick notes-->
      permalink: /:collection/:name

# https://jekyllrb.com/docs/configuration/liquid/
liquid:
  error_mode: strict
#  strict_variables: true
  strict_filters: true
